import { ReactPropTypes } from "react";
import { useState, useEffect } from "react";

const Home = ( )=> {

    const [posts, setPosts ] = useState([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);

    return(
        <div >
            <div className="home-header">
                <h1>Previously Generated Images</h1>
                <p>
                    Browse through a collection of images that have been generated by the community using AI.
                </p>
            </div>
            <main>
                <div className="search">
                    <label for="search">Search Images</label>
                    <input name="search" className="search" id="search"></input>
                </div>
                <section className="posts">
                    { posts && posts.map( post => (
                        <div className="card">

                        </div>
                    ) )}

                </section>
            </main>
            
        </div>
    )
}

export default Home;